### ISSUE TITLE
Docker compose Version failure

### ISSUE THREAD

**Issue by roswitina** [stephanelatil/savemail#1]
I had to customize the Docker Compose file a bit to make it work.I chanced the docker-compose.yml to

```
services:
  postgres_db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: savemail
      POSTGRES_PASSWORD: password
      POSTGRES_DB: savemaildb
    volumes:
      - psql_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U savemail -d savemaildb"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: stephanelatil/savemail-backend:0.1.1 ## add :0.1.1
    container_name: backend
    environment:
      SAVEMAIL__ConnectionStrings__Host: postgres_db
      SAVEMAIL__ConnectionStrings__Username: savemail
      SAVEMAIL__ConnectionStrings__Password: password
    volumes:
      - attachments_vol:/app/Attachments
    depends_on:
      postgres_db:
        condition: service_healthy
    ports:
      - "5000:5000"  # Assuming the backend listens on port 5000

  frontend:
    image: stephanelatil/savemail-frontend:0.1.1 ## add :0.1.1
    container_name: frontend
    environment:
      - PORT=3000
      - NEXT_PUBLIC_FRONTEND_URL=http://192.168.3.4:3000 ## <YOUR_IP_HOSTNAME_HERE>
      - NEXT_PUBLIC_BACKEND_URL=http://192.168.3.4:5000 ## <YOUR_IP_HOSTNAME_HERE>
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  attachments_vol:
  psql_data:
```

the frontend show the follow failure

```
frontend     |  ⨯ Error: Cannot find module 'next/dist/client/components/static-generation-async-storage.external.js'
frontend     | Require stack:
frontend     | - /app/.next/server/app/page.js
frontend     | - /app/node_modules/next/dist/server/require.js
frontend     | - /app/node_modules/next/dist/server/next-server.js
frontend     | - /app/node_modules/next/dist/server/next.js
frontend     | - /app/node_modules/next/dist/server/lib/start-server.js
frontend     | - /app/node_modules/next/dist/cli/next-start.js
frontend     |     at <unknown> (/app/node_modules/next/dist/server/require-hook.js:55:36)
frontend     |     at mod.require (/app/node_modules/next/dist/server/require-hook.js:65:28)
frontend     |     at 45869 (/app/.next/server/app/page.js:1:294)
frontend     |     at t (/app/.next/server/webpack-runtime.js:1:127) {
frontend     |   code: 'MODULE_NOT_FOUND',
frontend     |   requireStack: [Array]
frontend     | }
```

**Comment by stephanelatil** [comment]
Hi,

Sorry for the slow reply I was working on another project and forgot about this! (didn't think anyone would actually try it out!

I updated the images on dockerhub to reflect the latest changes and implemented some of your fixes! The docker compose should now work as of c652c38d3ef7214b25ed9ffa1536d4460688f465. (Only did a very quick test)

Thanks for the contribution!

**Comment by roswitina** [comment]
It may be that I misunderstand something or don't know enough about it and have therefore done it wrong. 

I started with the following docker-compose.yml file. I get the following messages. I noticed that the program outputs: FATAL: database “savemail” does not exist.

```
services:
  postgres_db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: savemail
      POSTGRES_PASSWORD: savemail
      POSTGRES_DB: savemaildb
    volumes:
      - psql_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 5


  backend:
    image: stephanelatil/savemail-backend:latest
    container_name: backend
    environment:
      SAVEMAIL__ConnectionStrings__Host: postgres_db # The name of the DB container or the Hostname of the psql DB
      SAVEMAIL__ConnectionStrings__Username: savemail
      SAVEMAIL__ConnectionStrings__Password: savemail
      # SAVEMAIL__OAuth2__GOOGLE_CLIENT_ID: #Google Client Id to enable Oauth linking. Otherwise Gmail addresses will not work!
      # SAVEMAIL__OAuth2__GOOGLE_CLIENT_SECRET: #Google Client Secret to enable Oauth linking. Otherwise Gmail addresses will not work!
      # SAVEMAIL__AttachmentsPath: #The directory path where the attachments will be stored. by default ./Attachments is used. The path is relative to the program.cs location
      # SAVEMAIL__AppSecret: # A random string of characters used to generate an encryption key for OAuth tokens. Do not modify this once is is set or all access and refresh tokens will become invalid. They can be regenerated by re-authent>
    volumes:
        - attachments_vol:/app/Attachments
    depends_on:
      postgres_db:
         condition: service_healthy

  frontend:
    image: stephanelatil/savemail-frontend:latest
    container_name: frontend
    environment:
      - PORT=3001
      - HOSTNAME=localhost
      - NEXT_PUBLIC_FRONTEND_URL="http://192.168.1.153:3000" #  my local address
      - NEXT_PUBLIC_BACKEND_URL="http://192.168.1.153:5000" # my local address
    depends_on:
        - backend
    ports:
        - "3000:3000"

volumes:
    attachments_vol:
    psql_data:
```

```
root@docker:/opt/savemail# docker compose up -d && docker compose logs -f
[+] Running 4/4
 ✔ Network savemail_default  Created                                                                                                                                                                                                       0.0s 
 ✔ Container postgres_db     Healthy                                                                                                                                                                                                      29.7s 
 ✔ Container backend         Started                                                                                                                                                                                                      21.1s 
 ✔ Container frontend        Started                                                                                                                                                                                                      11.0s 
postgres_db  | 
postgres_db  | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres_db  | 
postgres_db  | 2025-03-07 18:42:10.607 UTC [1] LOG:  starting PostgreSQL 15.12 (Debian 15.12-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
postgres_db  | 2025-03-07 18:42:10.607 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_db  | 2025-03-07 18:42:10.608 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_db  | 2025-03-07 18:42:10.609 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_db  | 2025-03-07 18:42:10.612 UTC [28] LOG:  database system was shut down at 2025-03-07 18:41:39 UTC
postgres_db  | 2025-03-07 18:42:10.616 UTC [1] LOG:  database system is ready to accept connections
postgres_db  | 2025-03-07 18:42:15.649 UTC [39] FATAL:  database "savemail" does not exist
backend      | warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
backend      |       Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed. For more information go to https://aka.ms/aspnet/dataprotectionwarning
backend      | info: Microsoft.EntityFrameworkCore.Migrations[20411]
backend      |       Acquiring an exclusive lock for migration application. See https://aka.ms/efcore-docs-migrations-lock for more information if this takes too long.
frontend     |    ▲ Next.js 15.2.1
frontend     |    - Local:        http://localhost:3001
frontend     |    - Network:      http://172.18.0.4:3001
frontend     | 
frontend     |  ✓ Starting...
frontend     |  ✓ Ready in 534ms
backend      | info: Microsoft.EntityFrameworkCore.Migrations[20405]
backend      |       No migrations were applied. The database is already up to date.
backend      | warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
backend      |       No XML encryptor configured. Key {d45abbf6-9323-4902-9ed7-6e11ea087429} may be persisted to storage in unencrypted form.
backend      | warn: Microsoft.AspNetCore.Hosting.Diagnostics[15]
backend      |       Overriding HTTP_PORTS '8080' and HTTPS_PORTS ''. Binding to values defined by URLS instead 'http://localhost:5000'.
backend      | info: Microsoft.Hosting.Lifetime[14]
backend      |       Now listening on: http://localhost:5000
backend      | info: Microsoft.Hosting.Lifetime[0]
backend      |       Application started. Press Ctrl+C to shut down.
backend      | info: Microsoft.Hosting.Lifetime[0]
backend      |       Hosting environment: Production
backend      | info: Microsoft.Hosting.Lifetime[0]
backend      |       Content root path: /app
backend      | warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
backend      |       Failed to determine the https port for redirect.
postgres_db  | 2025-03-07 18:42:20.725 UTC [49] FATAL:  database "savemail" does not exist
postgres_db  | 2025-03-07 18:42:25.815 UTC [57] FATAL:  database "savemail" does not exist
postgres_db  | 2025-03-07 18:42:30.892 UTC [66] FATAL:  database "savemail" does not exist
```

**Comment by stephanelatil** [comment]
That is strange...
The database name shoudl be `savemaildb` not `savemail`
I'll have a closer look tomorrow, I have 1-2 ideas to try and troubleshoot

**Comment by stephanelatil** [comment]
Update:
I made an error when setting the healthcheck for postgres!

> `test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d \${POSTGRES_PASSWORD}"]`

`-d $${POSTGRES_PASSWORD}` means the database is called the value of POSTGRES_PASSWORD. I should have used `-p`!
A quick fix is using this istead for the healthcheck test:

```
test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -p $${POSTGRES_PASSWORD} -d $${POSTGRES_DB}"]
```

**Notes** Also, the PORT environment var should be set to `3000` not `3001` on the frontend (or it might be unrechable). 
Make sure to set you IP in the HOSTNAME environment variable!

Try it out to see if it works! Thank for the bug reports! Much will change in the next few versions as it's still very much work in progress


I'll fix the clunky env vars soon!
Docs will be fixed in consequence 😃

**Comment by roswitina** [comment]
```
test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d \${POSTGRES_PASSWORD}"]
```
doesn't work for me. I get the following error message
```
root@docker:/opt/savemail# docker compose up -d && docker compose logs -f
[+] Running 4/4
 ✔ Network savemail_default  Created                                                                                                                                                                                                       0.0s 
 ✘ Container postgres_db     Error                                                                                                                                                                                                        25.7s 
 ✔ Container backend         Created                                                                                                                                                                                                       0.0s 
 ✔ Container frontend        Created                                                                                                                                                                                                       0.0s 
dependency failed to start: container postgres_db is unhealthy
root@docker:/opt/savemail# docker compose logs
postgres_db  | 
postgres_db  | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres_db  | 
postgres_db  | 2025-03-08 13:13:13.874 UTC [1] LOG:  starting PostgreSQL 15.12 (Debian 15.12-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
postgres_db  | 2025-03-08 13:13:13.875 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_db  | 2025-03-08 13:13:13.875 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_db  | 2025-03-08 13:13:13.878 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_db  | 2025-03-08 13:13:13.883 UTC [28] LOG:  database system was shut down at 2025-03-08 13:13:08 UTC
postgres_db  | 2025-03-08 13:13:13.888 UTC [1] LOG:  database system is ready to accept connections
```
That worked for me
```
healthcheck:
      # test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -p $${POSTGRES_PASSWORD} -d $${POSTGRES_DB}"]
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
```
This is the log output after start-up
```
root@docker:/opt/savemail# docker compose up -d && docker compose logs -f
[+] Running 4/4
 ✔ Network savemail_default  Created                                                                                                                                                                                                       0.0s 
 ✔ Container postgres_db     Healthy                                                                                                                                                                                                       5.7s 
 ✔ Container backend         Started                                                                                                                                                                                                       5.8s 
 ✔ Container frontend        Started                                                                                                                                                                                                       5.9s 
backend      | warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
backend      |       Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed. For more information go to https://aka.ms/aspnet/dataprotectionwarning
postgres_db  | 
postgres_db  | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres_db  | 
postgres_db  | 2025-03-08 13:23:15.986 UTC [1] LOG:  starting PostgreSQL 15.12 (Debian 15.12-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
postgres_db  | 2025-03-08 13:23:15.987 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_db  | 2025-03-08 13:23:15.987 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_db  | 2025-03-08 13:23:15.990 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_db  | 2025-03-08 13:23:15.994 UTC [28] LOG:  database system was shut down at 2025-03-08 13:23:12 UTC
postgres_db  | 2025-03-08 13:23:15.998 UTC [1] LOG:  database system is ready to accept connections
backend      | info: Microsoft.EntityFrameworkCore.Migrations[20411]
frontend     |    ▲ Next.js 15.2.1
frontend     |    - Local:        http://localhost:3000
frontend     |    - Network:      http://172.18.0.4:3000
frontend     | 
frontend     |  ✓ Starting...
frontend     |  ✓ Ready in 339ms
backend      |       Acquiring an exclusive lock for migration application. See https://aka.ms/efcore-docs-migrations-lock for more information if this takes too long.
backend      | info: Microsoft.EntityFrameworkCore.Migrations[20405]
backend      |       No migrations were applied. The database is already up to date.
backend      | warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
backend      |       No XML encryptor configured. Key {dd7836a4-51ef-4b4a-a408-2500d3034ade} may be persisted to storage in unencrypted form.
backend      | warn: Microsoft.AspNetCore.Hosting.Diagnostics[15]
backend      |       Overriding HTTP_PORTS '8080' and HTTPS_PORTS ''. Binding to values defined by URLS instead 'http://localhost:5000'.
backend      | info: Microsoft.Hosting.Lifetime[14]
backend      |       Now listening on: http://localhost:5000
backend      | info: Microsoft.Hosting.Lifetime[0]
backend      |       Application started. Press Ctrl+C to shut down.
backend      | info: Microsoft.Hosting.Lifetime[0]
backend      |       Hosting environment: Production
backend      | info: Microsoft.Hosting.Lifetime[0]
backend      |       Content root path: /app
backend      | warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
backend      |       Failed to determine the https port for redirect.
```
After that, I was shown a login window with the address http://192.168.1.104:5000, which also allowed me to create a new account. After opening the window and entering the data (username and twice the password) I confirmed this and the following error message was displayed at the top right. This message was displayed on a light red background. A login with this data was not possible and resulted in the same error message.
```
NetworkError when attempting to fetch resource.
```
